name: Flask CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            
            cd /home/ubuntu/flask-cicd || exit

            git pull origin main

            sudo apt update
            sudo apt install python3-pip python3-venv -y

           
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            
            source venv/bin/activate

            
            pip install --upgrade pip
            pip install -r requirements.txt

            
            pip install opencv-python

            pkill -f app.py || true

            nohup python3 instance/app.py > output.log 2>&1 &
